format:
  docx:
    toc: false
    geometry:
      - top=25mm
      - bottom=25mm
      - right=25mm
      - left=25mm
      - footskip=15mm
    extra_dependencies: ["float"]
    include-in-header:
      text: |
        \usepackage[format=plain,labelfont={bf},labelsep=period]{caption}
        \usepackage[hyperref=false,backref=false]{biblatex}
    reference-doc: csl/custom-reference-doc.docx
    mainfont: Helvetica
    sansfont: Helvetica
  html:
    toc: true
    comments:
      hypothesis: true

editor:
  render-on-save: false

execute:
  freeze: auto
  echo: false
  include: true
  warning: false
  message: false
  error: false
  cache: false
  
bibliography: [rreferences/not-peer-reviewed.bib references/papers.bib references/posters.bib references/talks.bib]
csl: csl/elsevier-harvard.csl
mainfont: Arial
sansfont: Arial

